Repository qfall/math, pull requests merged in 2023-05, with the labels that each got.

#216 Benchmark RSA
  benches/benchmarks.rs
  benches/classic_crypto.rs
  src/utils/sample/uniform.rs
Labels: enhancement📈, performance⚡

#224 Simplification for Q
  src/rational/q/rounding.rs
Labels: enhancement📈

#228 trace for MatZ
  src/error.rs
  src/integer/mat_z.rs
  src/integer/mat_z/trace.rs
Labels: enhancement📈

#238 initialize MatPolyRingZq
  src/integer_mod_q/mat_polynomial_ring_zq.rs
Labels: enhancement📈

#227 sub Q between types
  src/rational/q/arithmetic/sub.rs
Labels: enhancement📈

#242 Update CI to make crate caches available for PRs
  .github/workflows/main.yml
  .github/workflows/push.yml
Labels: workflow⚙️, hotfix🔥

#235 add Q between types
  src/rational/q/arithmetic/add.rs
Labels: enhancement📈

#244 fixing memory leak
  src/integer_mod_q/z_q/arithmetic/add.rs
Labels: hotfix🔥

#234 mul Zq between types
  src/integer_mod_q/z_q/arithmetic/mul.rs
Labels: enhancement📈

#237 div Q between types
  src/rational/q/arithmetic/div.rs
Labels: enhancement📈

#236 mul Q between types
  src/rational/q/arithmetic/mul.rs
Labels: enhancement📈

#226 Discrete Gaussian sampling
  src/error.rs
  src/rational/q/default.rs
  src/utils/sample.rs
  src/utils/sample/discrete_gauss.rs
Labels: enhancement📈

#233 sub Zq between types
  src/integer_mod_q/z_q/arithmetic/sub.rs
Labels: enhancement📈

#232 div Z between types
  src/integer/z/arithmetic/div.rs
Labels: enhancement📈

#231 mul Z between types
  src/integer/z/arithmetic/mul.rs
Labels: enhancement📈

#249 MatZ trace doc comment
  src/integer/mat_z/trace.rs
Labels: documentation📖

#241 trace for MatZq
  src/integer_mod_q/mat_zq.rs
  src/integer_mod_q/mat_zq/trace.rs
Labels: enhancement📈

#239 trace for MatQ
  src/rational/mat_q.rs
  src/rational/mat_q/trace.rs
Labels: enhancement📈

#240 trace for MatPolyZ
  src/integer/mat_poly_over_z.rs
  src/integer/mat_poly_over_z/trace.rs
Labels: enhancement📈

#246 Z `sample_discrete_gauss`
  src/integer/z/sample.rs
  src/integer/z/sample/discrete_gauss.rs
  src/integer/z/sample/uniform.rs
Labels: enhancement📈

#247 Zq `sample_discrete_gauss`
  Cargo.toml
  src/integer_mod_q/z_q/sample.rs
  src/integer_mod_q/z_q/sample/discrete_gauss.rs
  src/integer_mod_q/z_q/sample/uniform.rs
Labels: enhancement📈

#245 PolyOverZ `sample_uniform`
  src/integer/poly_over_z.rs
  src/integer/poly_over_z/sample.rs
  src/integer/poly_over_z/sample/uniform.rs
Labels: enhancement📈

#248 PolyOverZq `sample_uniform`
  src/integer_mod_q/poly_over_zq.rs
  src/integer_mod_q/poly_over_zq/sample.rs
  src/integer_mod_q/poly_over_zq/sample/uniform.rs
Labels: enhancement📈

#251 new for MatPolyRingZq
  src/integer_mod_q.rs
  src/integer_mod_q/mat_polynomial_ring_zq.rs
  src/integer_mod_q/mat_polynomial_ring_zq/from.rs
Labels: enhancement📈

#257 From for MatPolyRingZq
  src/integer_mod_q/mat_polynomial_ring_zq.rs
  src/integer_mod_q/mat_polynomial_ring_zq/default.rs
  src/integer_mod_q/mat_polynomial_ring_zq/from.rs
Labels: enhancement📈

#256 Conversion from PolyOverZ to PolyOverQ
  src/rational/poly_over_q/from.rs
Labels: enhancement📈

#264 Ensure that dev caches can be found by pull requests
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: workflow⚙️, hotfix🔥

#268 Rework qfromf64
  src/rational/mat_q/arithmetic/mul_scalar.rs
  src/rational/q/default.rs
  src/rational/q/distance.rs
  src/rational/q/from.rs
Labels: bug🐛

#267 Poly over q norms
  src/rational/poly_over_q.rs
  src/rational/poly_over_q/get.rs
  src/rational/poly_over_q/norm.rs
Labels: enhancement📈

#260 norms poly over z
  src/integer/poly_over_z.rs
  src/integer/poly_over_z/get.rs
  src/integer/poly_over_z/norm.rs
Labels: enhancement📈

#258 MatZ `swap` + `reverse`
  src/integer/mat_poly_over_z/set.rs
  src/integer/mat_z/set.rs
  src/integer_mod_q/mat_zq/set.rs
  src/rational/mat_q/set.rs
Labels: enhancement📈

#261 MatZq `swap` and `reverse`
  src/integer_mod_q/mat_zq/set.rs
Labels: enhancement📈

#263 MatPolyOverZ `swap` and `reverse`
  src/integer/mat_poly_over_z/set.rs
Labels: enhancement📈

#254 From q refactor
  src/integer/z/fmpz_helpers.rs
  src/integer_mod_q/z_q/fmpz_mod_helpers.rs
  src/rational/q.rs
  src/rational/q/cmp.rs
  src/rational/q/from.rs
  src/traits.rs
Labels: enhancement📈

#275 transpose for MatPolyRingZq
  src/integer_mod_q/mat_polynomial_ring_zq.rs
  src/integer_mod_q/mat_polynomial_ring_zq/transpose.rs
Labels: enhancement📈

#274 is_vector for MatPolyRingZq
  src/integer_mod_q/mat_polynomial_ring_zq.rs
  src/integer_mod_q/mat_polynomial_ring_zq/vector.rs
  src/integer_mod_q/mat_polynomial_ring_zq/vector/is_vector.rs
Labels: enhancement📈

#273 MatZ `set_row` and `set_column`
  src/integer/mat_z/set.rs
Labels: enhancement📈

#276 Add for MatPolyRingZq
  src/integer_mod_q/mat_polynomial_ring_zq.rs
  src/integer_mod_q/mat_polynomial_ring_zq/arithmetic.rs
  src/integer_mod_q/mat_polynomial_ring_zq/arithmetic/add.rs
Labels: enhancement📈

#283 Sqrt for `Q`
  src/integer/z/arithmetic/root.rs
  src/rational/q/arithmetic.rs
  src/rational/q/arithmetic/root.rs
Labels: enhancement📈

#288 Mul for MatQ and MatZ
  src/rational/mat_q/arithmetic/mul.rs
Labels: enhancement📈

#287 Mul for MatZq and MatZ
  src/integer_mod_q/mat_zq/arithmetic/mul.rs
Labels: enhancement📈

#278 Generic `sort` + MatZ `sort`
  src/integer/mat_poly_over_z/get.rs
  src/integer/mat_z.rs
  src/integer/mat_z/sort.rs
  src/integer/z/cmp.rs
Labels: enhancement📈

#279 MatZq `set_column` and `set_row`
  src/integer/mat_z/set.rs
  src/integer_mod_q/mat_zq/set.rs
  src/utils.rs
  src/utils/collective_evaluation.rs
Labels: enhancement📈

#280 MatQ `set_column` and `set_row`
  src/rational/mat_q/set.rs
Labels: enhancement📈

#281 MatPolyOverZ `set_column` and `set_row`
  src/integer/mat_poly_over_z/set.rs
Labels: enhancement📈

#291 MatQ `sort` + Q `Ord`
  src/rational/mat_q.rs
  src/rational/mat_q/sort.rs
  src/rational/q/cmp.rs
Labels: enhancement📈

#289 Refactor from for z
  src/integer/mat_z/sample.rs
  src/integer/poly_over_z/sample/uniform.rs
  src/integer/z/fmpz_helpers.rs
  src/integer/z/from.rs
  src/integer/z/sample/uniform.rs
  src/integer_mod_q/mat_zq/sample.rs
  src/integer_mod_q/modulus.rs
  src/integer_mod_q/modulus/fmpz_helpers.rs
  src/integer_mod_q/poly_over_zq/sample/uniform.rs
  src/integer_mod_q/z_q/distance.rs
  src/integer_mod_q/z_q/get.rs
  src/integer_mod_q/z_q/sample/uniform.rs
  src/macros/for_others.rs
Labels: enhancement📈
