Repository qfall/math, pull requests merged in 2023-06, with the labels that each got.

#294 Remove leftovers of Z::from(Zq) in benchmarks
  benches/classic_crypto.rs
Labels: bug🐛, hotfix🔥

#297 cargo clippy 0.1.70 falsely marks a clone as redundant.
  src/integer/z/arithmetic/root.rs
Labels: hotfix🔥

#304 Update dependencies
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  Cargo.toml
Labels: workflow⚙️, hotfix🔥

#300 MatZq `sample_discrete_gauss`
  src/integer/z/sample/discrete_gauss.rs
  src/integer_mod_q/mat_zq/sample.rs
  src/integer_mod_q/mat_zq/sample/discrete_gauss.rs
  src/integer_mod_q/mat_zq/sample/uniform.rs
Labels: enhancement📈

#301 MatZq `dot_product`
  src/integer_mod_q/mat_zq/vector.rs
  src/integer_mod_q/mat_zq/vector/dot_product.rs
Labels: enhancement📈

#284 Collect_entries for MatPolyRingZq
  src/integer/z/arithmetic/root.rs
  src/integer_mod_q/mat_polynomial_ring_zq/default.rs
  src/integer_mod_q/mat_polynomial_ring_zq/from.rs
  src/integer_mod_q/mat_polynomial_ring_zq/get.rs
  src/integer_mod_q/mat_polynomial_ring_zq/reduce.rs
  src/integer_mod_q/mat_polynomial_ring_zq/transpose.rs
  src/integer_mod_q/mat_polynomial_ring_zq/vector/is_vector.rs
  src/integer_mod_q/modulus_polynomial_ring_zq/cmp.rs
  src/integer_mod_q/polynomial_ring_zq/from.rs
  src/integer_mod_q/polynomial_ring_zq/reduce.rs
Labels: enhancement📈

#299 MatZ `sample_discrete_gauss`
  src/integer/mat_z/sample/discrete_gauss.rs
Labels: enhancement📈

#255 Conversions between PolyZ, PolyZq and PolynomialRingZq
  src/integer/poly_over_z/from.rs
  src/integer_mod_q/modulus_polynomial_ring_zq/get.rs
  src/integer_mod_q/poly_over_zq/from.rs
  src/integer_mod_q/polynomial_ring_zq.rs
  src/integer_mod_q/polynomial_ring_zq/from.rs
  src/integer_mod_q/polynomial_ring_zq/get.rs
Labels: enhancement📈

#305 Add `PolyOverQ` from `Into<Q>`
  src/rational/poly_over_q/from.rs
Labels: enhancement📈

#298 From basetype for PolyOverZ
  src/integer/poly_over_z/from.rs
Labels: enhancement📈

#307 Q_Numtraits
  src/rational/mat_q.rs
  src/rational/mat_q/properties.rs
  src/rational/poly_over_q.rs
  src/rational/poly_over_q/properties.rs
  src/rational/q/properties.rs
Labels: enhancement📈

#308 Zq numtraits
  src/integer_mod_q/mat_zq.rs
  src/integer_mod_q/mat_zq/properties.rs
  src/integer_mod_q/poly_over_zq/properties.rs
  src/integer_mod_q/z_q/properties.rs
Labels: enhancement📈

#316 First Version of Solve for Linear Equations mod q
  src/integer_mod_q/mat_zq.rs
  src/integer_mod_q/mat_zq/solve.rs
Labels: enhancement📈

#313 Z `sample_prime_uniform`
  src/integer/z/sample/uniform.rs
Labels: enhancement📈

#312 MatZq `sample_d`
  src/integer_mod_q/mat_zq/sample/discrete_gauss.rs
Labels: enhancement📈

#314 MatZ `sample_d_common`
  src/integer/mat_z/sample/discrete_gauss.rs
  src/utils/sample/discrete_gauss.rs
Labels: enhancement📈

#319 Rework from for modulus
  benches/classic_crypto.rs
  src/integer/mat_z/sample/uniform.rs
  src/integer/poly_over_z/sample/uniform.rs
  src/integer/z/distance.rs
  src/integer/z/from.rs
  src/integer/z/sample/uniform.rs
  src/integer_mod_q/mat_zq/from.rs
  src/integer_mod_q/mat_zq/get.rs
  src/integer_mod_q/modulus/cmp.rs
  src/integer_mod_q/modulus/from.rs
  src/integer_mod_q/poly_over_zq/sample/uniform.rs
  src/integer_mod_q/z_q/from.rs
Labels: enhancement📈

#311 Multiplication for MatPolyRingZq
  src/integer_mod_q/mat_polynomial_ring_zq/arithmetic.rs
  src/integer_mod_q/mat_polynomial_ring_zq/arithmetic/mul.rs
Labels: enhancement📈

#310 Concatenate for MatPolyRingZq
  src/integer_mod_q/mat_polynomial_ring_zq.rs
  src/integer_mod_q/mat_polynomial_ring_zq/concat.rs
Labels: enhancement📈

#317 Dot_product for MatPolyRingZq
  src/integer_mod_q/mat_polynomial_ring_zq/vector.rs
  src/integer_mod_q/mat_polynomial_ring_zq/vector/dot_product.rs
Labels: enhancement📈

#324 Remove unwraps that are no longer required
  src/integer_mod_q/mat_polynomial_ring_zq/concat.rs
Labels: hotfix🔥

#325 Error in benches
  benches/classic_crypto.rs
  src/integer_mod_q/modulus/from.rs
Labels: hotfix🔥

#327 Format doc comment function calls
  src/integer/mat_poly_over_z/cmp.rs
  src/integer/mat_poly_over_z/from.rs
  src/integer/mat_poly_over_z/get.rs
  src/integer/mat_z/cmp.rs
  src/integer/mat_z/get.rs
  src/integer/poly_over_z/cmp.rs
  src/integer/poly_over_z/evaluate.rs
  src/integer/z/arithmetic/add.rs
  src/integer/z/arithmetic/div.rs
  src/integer/z/cmp.rs
  src/integer/z/distance.rs
  src/integer/z/fmpz_helpers.rs
  src/integer/z/from.rs
  src/integer/z/gcd.rs
  src/integer/z/lcm.rs
  src/integer_mod_q/mat_polynomial_ring_zq/get.rs
  src/integer_mod_q/mat_zq/cmp.rs
  src/integer_mod_q/modulus_polynomial_ring_zq/cmp.rs
  src/integer_mod_q/poly_over_zq/cmp.rs
  src/integer_mod_q/poly_over_zq/set.rs
  src/integer_mod_q/z_q/distance.rs
  src/integer_mod_q/z_q/properties.rs
  src/rational/mat_q/cmp.rs
  src/rational/mat_q/get.rs
  src/rational/poly_over_q/cmp.rs
  src/rational/poly_over_q/from.rs
  src/rational/q/arithmetic/root.rs
  src/rational/q/cmp.rs
  src/rational/q/distance.rs
  src/rational/q/from.rs
  src/traits.rs
Labels: refactoring :tractor:

#329 hotfix arithmetic between types
  src/macros/arithmetics.rs
  src/rational/q/arithmetic/div.rs
Labels: bug🐛, hotfix🔥
