Repository qfall/math, pull requests merged in 2023-07, with the labels that each got.

#330 Exponential function optimization
  Cargo.toml
  benches/benchmarks.rs
  benches/sampling.rs
  src/rational/poly_over_q/ownership.rs
  src/rational/q/arithmetic/exp.rs
  src/rational/q/from.rs
  src/utils/sample/discrete_gauss.rs
Labels: performance⚡

#323 Q `log`
  src/error.rs
  src/integer/z/arithmetic/logarithm.rs
  src/rational/q/arithmetic.rs
  src/rational/q/arithmetic/logarithm.rs
  src/utils/sample/discrete_gauss.rs
Labels: enhancement📈

#334 Change the way ThreadRNG is used
  src/utils/sample/discrete_gauss.rs
  src/utils/sample/uniform.rs
Labels: bug🐛

#339 remove sort sampleD
  src/utils/sample/discrete_gauss.rs
Labels: bug🐛, hotfix🔥

#336 Refactor sprint 10
  benches/classic_crypto.rs
  src/integer/mat_poly_over_z/evaluate.rs
  src/integer/mat_z/sample/discrete_gauss.rs
  src/integer/mat_z/sample/uniform.rs
  src/integer/mat_z/set.rs
  src/integer/mat_z/sort.rs
  src/integer/mat_z/vector/dot_product.rs
  src/integer/poly_over_z.rs
  src/integer/poly_over_z/evaluate.rs
  src/integer/poly_over_z/sample/uniform.rs
  src/integer/poly_over_z/set.rs
  src/integer/z.rs
  src/integer/z/arithmetic/add.rs
  src/integer/z/arithmetic/div.rs
  src/integer/z/arithmetic/logarithm.rs
  src/integer/z/arithmetic/mul.rs
  src/integer/z/arithmetic/pow.rs
  src/integer/z/arithmetic/sub.rs
  src/integer/z/distance.rs
  src/integer/z/gcd.rs
  src/integer/z/lcm.rs
  src/integer/z/sample/discrete_gauss.rs
  src/integer/z/sample/uniform.rs
  src/integer_mod_q/mat_polynomial_ring_zq.rs
  src/integer_mod_q/mat_zq/get.rs
  src/integer_mod_q/mat_zq/sample/discrete_gauss.rs
  src/integer_mod_q/mat_zq/sample/uniform.rs
  src/integer_mod_q/mat_zq/set.rs
  src/integer_mod_q/mat_zq/sort.rs
  src/integer_mod_q/mat_zq/vector/dot_product.rs
  src/integer_mod_q/poly_over_zq/evaluate.rs
  src/integer_mod_q/poly_over_zq/sample/uniform.rs
  src/integer_mod_q/poly_over_zq/set.rs
  src/integer_mod_q/z_q/arithmetic/add.rs
  src/integer_mod_q/z_q/arithmetic/mul.rs
  src/integer_mod_q/z_q/arithmetic/pow.rs
  src/integer_mod_q/z_q/arithmetic/sub.rs
  src/integer_mod_q/z_q/distance.rs
  src/integer_mod_q/z_q/sample/discrete_gauss.rs
  src/integer_mod_q/z_q/sample/uniform.rs
  src/macros/arithmetics.rs
  src/macros/for_others.rs
  src/rational/mat_q/set.rs
  src/rational/mat_q/sort.rs
  src/rational/poly_over_q/evaluate.rs
  src/rational/poly_over_q/from.rs
  src/rational/poly_over_q/set.rs
  src/rational/q.rs
  src/rational/q/arithmetic/add.rs
  src/rational/q/arithmetic/div.rs
  src/rational/q/arithmetic/exp.rs
  src/rational/q/arithmetic/mul.rs
  src/rational/q/arithmetic/pow.rs
  src/rational/q/arithmetic/sub.rs
  src/rational/q/distance.rs
  src/rational/q/from.rs
  src/traits.rs
  src/utils/collective_evaluation.rs
  src/utils/sample/discrete_gauss.rs
Labels: refactoring :tractor:

#340 Correction of error messages
  src/error.rs
  src/integer/mat_poly_over_z/arithmetic/add.rs
  src/integer/mat_poly_over_z/arithmetic/sub.rs
  src/integer/mat_z/arithmetic/add.rs
  src/integer/mat_z/arithmetic/sub.rs
  src/integer_mod_q/mat_polynomial_ring_zq/arithmetic/add.rs
  src/integer_mod_q/mat_polynomial_ring_zq/arithmetic/mul.rs
  src/integer_mod_q/mat_zq/arithmetic/add.rs
  src/integer_mod_q/mat_zq/arithmetic/mul.rs
  src/integer_mod_q/mat_zq/arithmetic/mul_scalar.rs
  src/integer_mod_q/mat_zq/arithmetic/sub.rs
  src/integer_mod_q/mat_zq/tensor.rs
  src/integer_mod_q/poly_over_zq/arithmetic/add.rs
  src/integer_mod_q/poly_over_zq/arithmetic/mul.rs
  src/integer_mod_q/poly_over_zq/arithmetic/sub.rs
  src/integer_mod_q/polynomial_ring_zq/arithmetic/add.rs
  src/integer_mod_q/polynomial_ring_zq/arithmetic/mul.rs
  src/integer_mod_q/polynomial_ring_zq/arithmetic/sub.rs
  src/integer_mod_q/z_q/arithmetic/add.rs
  src/integer_mod_q/z_q/arithmetic/mul.rs
  src/integer_mod_q/z_q/arithmetic/sub.rs
  src/rational/mat_q/arithmetic/add.rs
  src/rational/mat_q/arithmetic/sub.rs
Labels: documentation📖, refactoring :tractor:

#343 fix documentation, as Zq does not implement Into<Z>
  src/integer/z.rs
  src/rational/q.rs
Labels: documentation📖

#338 Coefficient embedding for PolyOverZ + MatPolyOverZ
  src/integer/mat_poly_over_z.rs
  src/integer/mat_poly_over_z/coefficient_embedding.rs
  src/integer/poly_over_z.rs
  src/integer/poly_over_z/coefficient_embedding.rs
  src/traits.rs
Labels: enhancement📈

#331 SampleD Ring-Variant
  src/integer/mat_poly_over_z.rs
  src/integer/mat_poly_over_z/sample.rs
  src/integer/mat_poly_over_z/sample/discrete_gauss.rs
  src/integer_mod_q/mat_polynomial_ring_zq.rs
  src/integer_mod_q/mat_polynomial_ring_zq/sample.rs
  src/integer_mod_q/mat_polynomial_ring_zq/sample/discrete_gauss.rs
  src/utils/sample/discrete_gauss.rs
Labels: enhancement📈

#335 Inverse for MatZq with prime modulus
  src/integer_mod_q/mat_zq.rs
  src/integer_mod_q/mat_zq/inverse.rs
Labels: enhancement📈

#333 Division for MatZ by Z
  src/integer/mat_z/arithmetic.rs
  src/integer/mat_z/arithmetic/div.rs
Labels: enhancement📈

#352 Tensor product for MatPolyOverZ
  src/integer/mat_poly_over_z.rs
  src/integer/mat_poly_over_z/tensor.rs
  src/integer/mat_z/tensor.rs
  src/integer_mod_q/mat_zq/tensor.rs
Labels: enhancement📈

#344 dot_product for MatPolyZ
  src/integer/mat_poly_over_z/vector.rs
  src/integer/mat_poly_over_z/vector/dot_product.rs
Labels: enhancement📈

#347 dot_product for PolyOverQ
  src/rational/poly_over_q.rs
  src/rational/poly_over_q/dot_product.rs
Labels: enhancement📈

#346 dot_product for PolyOverZ
  src/integer/poly_over_z.rs
  src/integer/poly_over_z/dot_product.rs
Labels: enhancement📈

#345 dot_product for PolyOverZq
  src/integer_mod_q/poly_over_zq.rs
  src/integer_mod_q/poly_over_zq/dot_product.rs
  src/integer_mod_q/poly_over_zq/get.rs
Labels: enhancement📈

#357 Window Function for MatZ
  src/integer/mat_z/get.rs
Labels: enhancement📈

#351 Display trait to polynomial rings using derive_more
  Cargo.toml
  src/integer_mod_q/mat_polynomial_ring_zq.rs
  src/integer_mod_q/polynomial_ring_zq.rs
Labels: enhancement📈

#360 Submatrix for other Matrix Types
  src/integer/mat_poly_over_z/get.rs
  src/integer_mod_q/mat_polynomial_ring_zq/get.rs
  src/integer_mod_q/mat_zq/get.rs
  src/rational/mat_q/get.rs
Labels: enhancement📈

#359 Sample d ring fix
  src/integer/mat_poly_over_z/sample/discrete_gauss.rs
  src/integer_mod_q/mat_polynomial_ring_zq/sample/discrete_gauss.rs
Labels: bug🐛

#361 Get_row and Get_column for MatPolynomialRingZq
  src/integer_mod_q/mat_polynomial_ring_zq/get.rs
Labels: enhancement📈

#350 get_mat for MatPolynomialRingZq
  src/integer_mod_q/mat_polynomial_ring_zq/get.rs
Labels: enhancement📈

#337 Add negative indexing for Matrix entries.
  src/integer/mat_poly_over_z/get.rs
  src/integer/mat_poly_over_z/set.rs
  src/integer/mat_z/get.rs
  src/integer/mat_z/set.rs
  src/integer_mod_q/mat_polynomial_ring_zq/get.rs
  src/integer_mod_q/mat_polynomial_ring_zq/set.rs
  src/integer_mod_q/mat_zq/get.rs
  src/integer_mod_q/mat_zq/set.rs
  src/rational/mat_q/get.rs
  src/rational/mat_q/set.rs
  src/utils/index.rs
Labels: enhancement📈

#355 Sub for MatPolyRingZq
  src/integer_mod_q/mat_polynomial_ring_zq/arithmetic.rs
  src/integer_mod_q/mat_polynomial_ring_zq/arithmetic/sub.rs
Labels: enhancement📈
