Repository qfall/math, pull requests merged in 2023-09, with the labels that each got.

#389 Module and Crate Description
  src/integer.rs
  src/integer_mod_q.rs
  src/lib.rs
  src/rational.rs
Labels: documentation📖

#382 MatZ `sample_binomial`
  src/integer/mat_z/sample.rs
  src/integer/mat_z/sample/binomial.rs
Labels: enhancement📈

#383 MatZq `sample_binomial`
  src/integer_mod_q/mat_zq/sample.rs
  src/integer_mod_q/mat_zq/sample/binomial.rs
Labels: enhancement📈

#384 PolyOverZ + PolynomialRingZq `sample_binomial`
  src/integer/poly_over_z/sample.rs
  src/integer/poly_over_z/sample/binomial.rs
  src/integer/poly_over_z/sample/uniform.rs
  src/integer_mod_q/polynomial_ring_zq/sample.rs
  src/integer_mod_q/polynomial_ring_zq/sample/binomial.rs
Labels: enhancement📈

#385 PolyOverZq `sample_binomial`
  src/integer_mod_q/poly_over_zq/sample.rs
  src/integer_mod_q/poly_over_zq/sample/binomial.rs
Labels: enhancement📈

#391 binomial and uniform sampling for MatPolyOverZ and MatPolyRingZq
  src/integer/mat_poly_over_z/sample.rs
  src/integer/mat_poly_over_z/sample/binomial.rs
  src/integer/mat_poly_over_z/sample/uniform.rs
  src/integer_mod_q/mat_polynomial_ring_zq/sample.rs
  src/integer_mod_q/mat_polynomial_ring_zq/sample/binomial.rs
  src/integer_mod_q/mat_polynomial_ring_zq/sample/uniform.rs
Labels: enhancement📈

#390 Update README.md
  README.md
Labels: documentation📖

#379 Get closest to zero representative
  src/integer/mat_z/from.rs
  src/integer_mod_q/mat_zq/get.rs
Labels: enhancement📈

#387 MatPolyRingZq scalar multiplication
  src/integer/mat_poly_over_z/ownership.rs
  src/integer_mod_q/mat_polynomial_ring_zq/arithmetic.rs
  src/integer_mod_q/mat_polynomial_ring_zq/arithmetic/mul_scalar.rs
Labels: enhancement📈

#393 Refactor Errors
  src/error.rs
  src/integer/mat_poly_over_z/from.rs
  src/integer/mat_poly_over_z/vector/dot_product.rs
  src/integer/mat_z/from.rs
  src/integer/mat_z/sample/discrete_gauss.rs
  src/integer/mat_z/sort.rs
  src/integer/mat_z/vector/dot_product.rs
  src/integer/poly_over_z/from.rs
  src/integer/z/arithmetic/logarithm.rs
  src/integer/z/arithmetic/root.rs
  src/integer/z/from.rs
  src/integer_mod_q/mat_polynomial_ring_zq/vector/dot_product.rs
  src/integer_mod_q/mat_zq/from.rs
  src/integer_mod_q/mat_zq/sample/discrete_gauss.rs
  src/integer_mod_q/mat_zq/sort.rs
  src/integer_mod_q/mat_zq/vector/dot_product.rs
  src/integer_mod_q/modulus/from.rs
  src/integer_mod_q/poly_over_zq/from.rs
  src/integer_mod_q/z_q/from.rs
  src/rational/mat_q/from.rs
  src/rational/mat_q/sort.rs
  src/rational/mat_q/vector/dot_product.rs
  src/rational/poly_over_q/from.rs
  src/rational/q/arithmetic/logarithm.rs
  src/rational/q/arithmetic/root.rs
  src/rational/q/from.rs
  src/utils/dimensions.rs
  src/utils/parse.rs
  src/utils/sample/discrete_gauss.rs
Labels: refactoring :tractor:

#394 Refactor macros
  benches/classic_crypto.rs
  src/integer/mat_poly_over_z/get.rs
  src/integer/z/arithmetic/div.rs
  src/integer/z/cmp.rs
  src/integer/z/from.rs
  src/integer_mod_q/mat_polynomial_ring_zq/default.rs
  src/integer_mod_q/mat_polynomial_ring_zq/reduce.rs
  src/macros/for_others.rs
  src/rational/q/arithmetic/logarithm.rs
  src/rational/q/cmp.rs
  src/utils/dimensions.rs
  src/utils/sample/binomial.rs
  src/utils/sample/uniform.rs
Labels: refactoring :tractor:

#395 Fixed TODOs
  README.md
  src/integer/mat_z/inverse.rs
  src/integer_mod_q/mat_polynomial_ring_zq/default.rs
  src/integer_mod_q/poly_over_zq/norm.rs
  src/integer_mod_q/z_q/distance.rs
  src/integer_mod_q/z_q/from.rs
  src/rational/poly_over_q/evaluate.rs
  src/rational/poly_over_q/norm.rs
  src/utils/sample/discrete_gauss.rs
Labels: refactoring :tractor:

#398 Update readme
  README.md
Labels: refactoring :tractor:
