Repository qfall/math, pull requests merged in 2023-08, with the labels that each got.

#356 Setter for PolyRingZq
  src/integer/poly_over_z/set.rs
  src/integer_mod_q/poly_over_zq/set.rs
  src/integer_mod_q/polynomial_ring_zq.rs
  src/integer_mod_q/polynomial_ring_zq/set.rs
  src/rational/poly_over_q/set.rs
Labels: enhancement📈

#365 Reduce Polynomials by Polynomials
  src/integer/mat_poly_over_z.rs
  src/integer/mat_poly_over_z/reduce.rs
  src/integer/poly_over_z.rs
  src/integer/poly_over_z/fmpz_poly_helpers.rs
  src/integer/poly_over_z/reduce.rs
Labels: enhancement📈

#364 Factorization for Integers
  src/utils.rs
  src/utils/factorization.rs
  src/utils/factorization/default.rs
  src/utils/factorization/from.rs
  src/utils/factorization/ownership.rs
  src/utils/factorization/refine.rs
  src/utils/factorization/to_string.rs
Labels: enhancement📈

#367 Z `to_bits`, `from_bits`, `modulo`
  src/integer/z/from.rs
  src/integer/z/properties.rs
Labels: enhancement📈

#370 Update Interfaces
  src/integer/mat_poly_over_z.rs
  src/integer/mat_poly_over_z/arithmetic/mul_scalar.rs
  src/integer/mat_poly_over_z/default.rs
  src/integer/mat_poly_over_z/trace.rs
  src/integer/poly_over_z/arithmetic/mul.rs
  src/integer/poly_over_z/cmp.rs
  src/integer/poly_over_z/dot_product.rs
  src/integer/poly_over_z/from.rs
  src/integer/poly_over_z/get.rs
  src/integer/poly_over_z/norm.rs
  src/integer/poly_over_z/properties.rs
  src/integer/poly_over_z/sample/discrete_gauss.rs
  src/integer_mod_q/mat_polynomial_ring_zq/default.rs
  src/integer_mod_q/mat_polynomial_ring_zq/from.rs
  src/integer_mod_q/mat_polynomial_ring_zq/get.rs
  src/integer_mod_q/mat_zq/from.rs
  src/integer_mod_q/modulus_polynomial_ring_zq/from.rs
  src/integer_mod_q/poly_over_zq/sample/discrete_gauss.rs
  src/integer_mod_q/polynomial_ring_zq/arithmetic/mul.rs
  src/integer_mod_q/polynomial_ring_zq/from.rs
  src/integer_mod_q/polynomial_ring_zq/get.rs
  src/integer_mod_q/polynomial_ring_zq/set.rs
  src/integer_mod_q/z_q/from.rs
Labels: documentation📖, enhancement📈

#371 Sample_d with precomputed GSO
  src/integer/mat_z/sample/discrete_gauss.rs
  src/integer_mod_q/mat_zq/sample/discrete_gauss.rs
  src/utils/sample/discrete_gauss.rs
Labels: enhancement📈, performance⚡

#369 Solve for MatZq
  src/integer_mod_q.rs
  src/integer_mod_q/mat_zq/set.rs
  src/integer_mod_q/mat_zq/solve.rs
  src/utils/collective_evaluation.rs
Labels: enhancement📈

#374 Z `is_perfect_power`
  src/integer/z/properties.rs
Labels: enhancement📈

#376 Binomial Sampling
  Cargo.toml
  src/utils/sample.rs
  src/utils/sample/binomial.rs
  src/utils/sample/discrete_gauss.rs
Labels: enhancement📈

#375 Inverse for MatZq
  src/integer_mod_q/mat_zq/inverse.rs
Labels: enhancement📈

#373 Add Struct descriptions to PolynomialRings + fix bug
  src/integer_mod_q/mat_polynomial_ring_zq.rs
  src/integer_mod_q/mat_polynomial_ring_zq/set.rs
  src/integer_mod_q/modulus_polynomial_ring_zq.rs
  src/integer_mod_q/polynomial_ring_zq.rs
Labels: bug🐛, documentation📖

#386 MatPolyRingZq properties
  src/integer_mod_q/mat_polynomial_ring_zq.rs
  src/integer_mod_q/mat_polynomial_ring_zq/properties.rs
  src/integer_mod_q/mat_zq/properties.rs
Labels: enhancement📈

#388 Tensor product for MatQ
  src/rational/mat_q.rs
  src/rational/mat_q/tensor.rs
Labels: enhancement📈

#381 Zq `sample_binomial`
  src/integer_mod_q/z_q/sample.rs
  src/integer_mod_q/z_q/sample/binomial.rs
Labels: enhancement📈

#380 Z `sample_binomial`
  src/integer/z/sample.rs
  src/integer/z/sample/binomial.rs
Labels: enhancement📈
