Repository qfall/math, pull requests merged in 2024-09, with the labels that each got.

#401 Continuous Gaussian Sample for MatQ
  src/rational/mat_q.rs
  src/rational/mat_q/sample.rs
  src/rational/mat_q/sample/gauss.rs
Labels: enhancement📈

#406 refactoring of math
  README.md
  benches/sampling.rs
  src/integer/mat_poly_over_z/arithmetic/mul.rs
  src/integer/mat_poly_over_z/arithmetic/mul_scalar.rs
  src/integer/mat_z/arithmetic/div.rs
  src/integer/mat_z/arithmetic/mul.rs
  src/integer/mat_z/arithmetic/mul_scalar.rs
  src/integer/mat_z/concat.rs
  src/integer/mat_z/from.rs
  src/integer/poly_over_z/from.rs
  src/integer/z.rs
  src/integer/z/fmpz_helpers.rs
  src/integer/z/from.rs
  src/integer_mod_q/mat_polynomial_ring_zq.rs
  src/integer_mod_q/mat_polynomial_ring_zq/arithmetic/mul.rs
  src/integer_mod_q/mat_polynomial_ring_zq/arithmetic/mul_scalar.rs
  src/integer_mod_q/mat_polynomial_ring_zq/concat.rs
  src/integer_mod_q/mat_zq/arithmetic/mul.rs
  src/integer_mod_q/mat_zq/arithmetic/mul_scalar.rs
  src/integer_mod_q/mat_zq/concat.rs
  src/integer_mod_q/mat_zq/from.rs
  src/integer_mod_q/mat_zq/get.rs
  src/integer_mod_q/modulus/from.rs
  src/integer_mod_q/modulus/to_string.rs
  src/integer_mod_q/modulus_polynomial_ring_zq/to_string.rs
  src/integer_mod_q/poly_over_zq/evaluate.rs
  src/integer_mod_q/poly_over_zq/from.rs
  src/integer_mod_q/poly_over_zq/to_string.rs
  src/integer_mod_q/z_q.rs
  src/macros/arithmetics.rs
  src/macros/for_others.rs
  src/macros/from.rs
  src/macros/serialize.rs
  src/rational/mat_q/arithmetic/mul.rs
  src/rational/mat_q/arithmetic/mul_scalar.rs
  src/rational/mat_q/from.rs
  src/rational/poly_over_q/from.rs
  src/rational/q.rs
  src/traits.rs
Labels: documentation📖

#409 Get_mat for MatZq
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  src/integer/mat_z/from.rs
  src/integer_mod_q/mat_zq/get.rs
  src/integer_mod_q/mat_zq/inverse.rs
  src/integer_mod_q/mat_zq/sample/discrete_gauss.rs
  src/integer_mod_q/mat_zq/solve.rs
Labels: enhancement📈

#414 From for String
  src/integer/mat_poly_over_z/to_string.rs
  src/integer/mat_z/arithmetic/div.rs
  src/integer/mat_z/to_string.rs
  src/integer/poly_over_z/to_string.rs
  src/integer/z/to_string.rs
  src/integer_mod_q/mat_zq/get.rs
  src/integer_mod_q/mat_zq/solve.rs
  src/integer_mod_q/mat_zq/to_string.rs
  src/integer_mod_q/modulus/to_string.rs
  src/integer_mod_q/modulus_polynomial_ring_zq/to_string.rs
  src/integer_mod_q/poly_over_zq/to_string.rs
  src/integer_mod_q/z_q/to_string.rs
  src/macros/for_others.rs
  src/rational/mat_q/to_string.rs
  src/rational/poly_over_q/to_string.rs
  src/rational/q/to_string.rs
Labels: bug🐛, enhancement📈

#407 SampleD with a non-spherical Gaussian convolution matrix (with standard base and center 0)
  src/integer/mat_z/sample/discrete_gauss.rs
Labels: enhancement📈

#417 From for owned types
  src/integer/mat_poly_over_z/from.rs
  src/integer/mat_poly_over_z/vector/dot_product.rs
  src/integer/mat_z/from.rs
  src/integer/mat_z/vector/dot_product.rs
  src/integer/mat_z/vector/norm.rs
  src/integer/poly_over_z/from.rs
  src/integer/z/arithmetic/root.rs
  src/integer/z/default.rs
  src/integer/z/distance.rs
  src/integer/z/from.rs
  src/integer_mod_q/mat_polynomial_ring_zq/from.rs
  src/integer_mod_q/mat_polynomial_ring_zq/vector/dot_product.rs
  src/integer_mod_q/mat_zq/from.rs
  src/integer_mod_q/mat_zq/set.rs
  src/integer_mod_q/mat_zq/vector/dot_product.rs
  src/integer_mod_q/mat_zq/vector/norm.rs
  src/integer_mod_q/modulus_polynomial_ring_zq/from.rs
  src/integer_mod_q/poly_over_zq/evaluate.rs
  src/integer_mod_q/poly_over_zq/from.rs
  src/integer_mod_q/polynomial_ring_zq/from.rs
  src/integer_mod_q/z_q/from.rs
  src/rational/mat_q/from.rs
  src/rational/mat_q/set.rs
  src/rational/mat_q/vector/dot_product.rs
  src/rational/mat_q/vector/norm.rs
  src/rational/poly_over_q/from.rs
  src/rational/q/arithmetic/root.rs
  src/rational/q/distance.rs
  src/rational/q/from.rs
  src/utils/factorization/default.rs
  src/utils/factorization/from.rs
Labels: enhancement📈

#412 Make `Q::simplify` more viable
  src/rational/q/default.rs
  src/rational/q/rounding.rs
Labels: documentation📖, enhancement📈

#416 Conversion between UTF8-encoded `Strings` and `Z`
  src/integer/z/from.rs
  src/integer/z/to_string.rs
  src/utils/sample/binomial.rs
Labels: enhancement📈
