Repository qfall/math, pull requests merged in 2025-03, with the labels that each got.

#467 Optimize Uniform Sampling
  benches/benchmarks.rs
  benches/uniform.rs
  src/integer/mat_z/sample/uniform.rs
  src/integer/poly_over_z/sample/uniform.rs
  src/integer/z/from.rs
  src/integer/z/sample/uniform.rs
  src/integer_mod_q/mat_zq/sample/uniform.rs
  src/integer_mod_q/poly_over_zq/sample/uniform.rs
  src/integer_mod_q/z_q/sample/uniform.rs
  src/utils/sample.rs
  src/utils/sample/discrete_gauss.rs
  src/utils/sample/uniform.rs
Labels: performance⚡

#471 Add `set_entry_unchecked`
  src/integer/mat_poly_over_z/coefficient_embedding.rs
  src/integer/mat_poly_over_z/from.rs
  src/integer/mat_poly_over_z/sample/binomial.rs
  src/integer/mat_poly_over_z/sample/uniform.rs
  src/integer/mat_poly_over_z/set.rs
  src/integer/mat_z/from.rs
  src/integer/mat_z/sample/binomial.rs
  src/integer/mat_z/sample/discrete_gauss.rs
  src/integer/mat_z/sample/uniform.rs
  src/integer/mat_z/set.rs
  src/integer/poly_over_z/coefficient_embedding.rs
  src/integer_mod_q/mat_polynomial_ring_zq/set.rs
  src/integer_mod_q/mat_zq/from.rs
  src/integer_mod_q/mat_zq/get.rs
  src/integer_mod_q/mat_zq/sample/binomial.rs
  src/integer_mod_q/mat_zq/sample/discrete_gauss.rs
  src/integer_mod_q/mat_zq/sample/uniform.rs
  src/integer_mod_q/mat_zq/set.rs
  src/integer_mod_q/mat_zq/solve.rs
  src/integer_mod_q/modulus_polynomial_ring_zq/coefficient_embedding.rs
  src/integer_mod_q/poly_over_zq/coefficient_embedding.rs
  src/macros/for_others.rs
  src/rational/mat_q/cholesky_decomp.rs
  src/rational/mat_q/rounding.rs
  src/rational/mat_q/sample/gauss.rs
  src/rational/mat_q/set.rs
  src/rational/poly_over_q/coefficient_embedding.rs
  src/traits.rs
Labels: performance⚡

#470 Normal Forms for `MatZ`
  src/integer/mat_z.rs
  src/integer/mat_z/forms.rs
Labels: enhancement📈

#469 Bitlogic for `Z`
  src/integer/z.rs
  src/integer/z/logic.rs
  src/integer/z/logic/bit_and.rs
  src/integer/z/logic/bit_or.rs
  src/integer/z/logic/bit_xor.rs
  src/integer/z/logic/complement.rs
Labels: enhancement📈

#449 PolynomialRingZq coefficient embedding
  src/integer/mat_poly_over_z/coefficient_embedding.rs
  src/integer/mat_poly_over_z/sample/discrete_gauss.rs
  src/integer/poly_over_z/coefficient_embedding.rs
  src/integer_mod_q/poly_over_zq/coefficient_embedding.rs
  src/integer_mod_q/polynomial_ring_zq.rs
  src/integer_mod_q/polynomial_ring_zq/coefficient_embedding.rs
  src/rational/poly_over_q/coefficient_embedding.rs
Labels: enhancement📈

#450 MatPolyRingZq coefficient embedding
  src/integer_mod_q/mat_polynomial_ring_zq.rs
  src/integer_mod_q/mat_polynomial_ring_zq/coefficient_embedding.rs
Labels: enhancement📈

#464 Replace fmpz_set by fmpz_init_set
  src/integer/mat_z/get.rs
  src/integer/z/fmpz_helpers.rs
  src/integer/z/from.rs
  src/integer/z/ownership.rs
  src/integer_mod_q/mat_zq/get.rs
  src/integer_mod_q/modulus_polynomial_ring_zq/get.rs
  src/integer_mod_q/modulus_polynomial_ring_zq/to_string.rs
  src/rational/q/from.rs
  src/rational/q/get.rs
Labels: performance⚡

#460 PartialOrd between Z, Q and Modulus
  src/integer/mat_poly_over_z/sample/binomial.rs
  src/integer/mat_z/sample/binomial.rs
  src/integer/poly_over_z/sample/binomial.rs
  src/integer/z/cmp.rs
  src/integer_mod_q/mat_polynomial_ring_zq/sample/binomial.rs
  src/integer_mod_q/mat_polynomial_ring_zq/sample/uniform.rs
  src/integer_mod_q/mat_zq/sample/binomial.rs
  src/integer_mod_q/mat_zq/sample/uniform.rs
  src/integer_mod_q/modulus/cmp.rs
  src/integer_mod_q/poly_over_zq/sample/binomial.rs
  src/integer_mod_q/poly_over_zq/sample/discrete_gauss.rs
  src/integer_mod_q/polynomial_ring_zq/sample/binomial.rs
  src/macros/for_others.rs
  src/rational/q/cmp.rs
  src/rational/q/rounding.rs
  src/rational/q/sample/gauss.rs
  src/utils/sample/discrete_gauss.rs
Labels: enhancement📈

#458 LLL
  benches/basis_reductions.rs
  benches/benchmarks.rs
  benches/cholesky_decomposition.rs
  benches/sample_z.rs
  src/integer/mat_z.rs
  src/integer/mat_z/basis_reductions.rs
Labels: enhancement📈

#472 Implement `AddAssign` for simple types
  benches/integer.rs
  src/integer/mat_poly_over_z/vector/norm.rs
  src/integer/poly_over_z/arithmetic/add.rs
  src/integer/poly_over_z/norm.rs
  src/integer/z/arithmetic/add.rs
  src/integer_mod_q/poly_over_zq/arithmetic/add.rs
  src/integer_mod_q/poly_over_zq/norm.rs
  src/integer_mod_q/polynomial_ring_zq/arithmetic/add.rs
  src/integer_mod_q/polynomial_ring_zq/norm.rs
  src/integer_mod_q/z_q/arithmetic/add.rs
  src/macros/arithmetics.rs
  src/rational/poly_over_q/arithmetic/add.rs
  src/rational/poly_over_q/norm.rs
  src/rational/q/arithmetic/add.rs
Labels: enhancement📈, performance⚡

#473 `get_entry_unchecked` for all Matrix Types
  src/integer/mat_poly_over_z/coefficient_embedding.rs
  src/integer/mat_poly_over_z/from.rs
  src/integer/mat_poly_over_z/get.rs
  src/integer/mat_poly_over_z/properties.rs
  src/integer/mat_poly_over_z/tensor.rs
  src/integer/mat_poly_over_z/vector/norm.rs
  src/integer/mat_z/get.rs
  src/integer/mat_z/properties.rs
  src/integer/mat_z/to_string.rs
  src/integer/poly_over_z/coefficient_embedding.rs
  src/integer_mod_q/mat_polynomial_ring_zq/coefficient_embedding.rs
  src/integer_mod_q/mat_polynomial_ring_zq/get.rs
  src/integer_mod_q/mat_polynomial_ring_zq/properties.rs
  src/integer_mod_q/mat_polynomial_ring_zq/tensor.rs
  src/integer_mod_q/mat_polynomial_ring_zq/vector/norm.rs
  src/integer_mod_q/mat_zq/get.rs
  src/integer_mod_q/mat_zq/properties.rs
  src/integer_mod_q/mat_zq/solve.rs
  src/integer_mod_q/mat_zq/to_string.rs
  src/integer_mod_q/poly_over_zq/coefficient_embedding.rs
  src/integer_mod_q/polynomial_ring_zq/coefficient_embedding.rs
  src/rational/mat_q/cholesky_decomp.rs
  src/rational/mat_q/get.rs
  src/rational/mat_q/properties.rs
  src/rational/mat_q/rounding.rs
  src/rational/poly_over_q/coefficient_embedding.rs
  src/traits.rs
Labels: performance⚡

#475 Make `set_entry_unchecked` unsafe
  src/integer/mat_poly_over_z/coefficient_embedding.rs
  src/integer/mat_poly_over_z/from.rs
  src/integer/mat_poly_over_z/sample/binomial.rs
  src/integer/mat_poly_over_z/sample/uniform.rs
  src/integer/mat_poly_over_z/set.rs
  src/integer/mat_z/from.rs
  src/integer/mat_z/sample/binomial.rs
  src/integer/mat_z/sample/discrete_gauss.rs
  src/integer/mat_z/sample/uniform.rs
  src/integer/mat_z/set.rs
  src/integer/poly_over_z/coefficient_embedding.rs
  src/integer_mod_q/mat_polynomial_ring_zq/set.rs
  src/integer_mod_q/mat_zq/from.rs
  src/integer_mod_q/mat_zq/get.rs
  src/integer_mod_q/mat_zq/sample/binomial.rs
  src/integer_mod_q/mat_zq/sample/discrete_gauss.rs
  src/integer_mod_q/mat_zq/sample/uniform.rs
  src/integer_mod_q/mat_zq/set.rs
  src/integer_mod_q/mat_zq/solve.rs
  src/integer_mod_q/modulus_polynomial_ring_zq/coefficient_embedding.rs
  src/integer_mod_q/poly_over_zq/coefficient_embedding.rs
  src/integer_mod_q/polynomial_ring_zq/coefficient_embedding.rs
  src/macros/for_others.rs
  src/rational/mat_q/cholesky_decomp.rs
  src/rational/mat_q/rounding.rs
  src/rational/mat_q/sample/gauss.rs
  src/rational/mat_q/set.rs
  src/rational/poly_over_q/coefficient_embedding.rs
  src/traits.rs
Labels: bug🐛

#479 From PolyOverZq for PolyRingZq
  src/integer_mod_q/polynomial_ring_zq/from.rs
Labels: enhancement📈

#480 PartialEq between MatZ and MatQ
  src/integer/mat_z/forms.rs
  src/integer/mat_z/serialize.rs
  src/rational/mat_q/cmp.rs
  src/rational/mat_q/serialize.rs
Labels: enhancement📈

#478 `AddAssign` for Matrices
  src/integer/mat_poly_over_z/arithmetic/add.rs
  src/integer/mat_z/arithmetic/add.rs
  src/integer_mod_q/mat_polynomial_ring_zq/arithmetic/add.rs
  src/integer_mod_q/mat_zq/arithmetic/add.rs
  src/integer_mod_q/mat_zq/solve.rs
  src/rational/mat_q/arithmetic/add.rs
Labels: enhancement📈, performance⚡
