Repository qfall/math, pull requests merged in 2025-05, with the labels that each got.

#490 Missing `AddAssign` implementations between types
  src/integer/z/arithmetic/add.rs
  src/integer_mod_q/mat_polynomial_ring_zq/arithmetic/add.rs
  src/integer_mod_q/mat_zq/arithmetic/add.rs
  src/integer_mod_q/poly_over_zq/arithmetic/add.rs
  src/integer_mod_q/polynomial_ring_zq/arithmetic/add.rs
  src/integer_mod_q/z_q/arithmetic/add.rs
  src/rational/mat_q/arithmetic/add.rs
  src/rational/poly_over_q/arithmetic/add.rs
  src/rational/q/arithmetic/add.rs
Labels: enhancement📈

#500 Implement SetSubmatrix Trait for all Matrices
  src/integer/mat_poly_over_z/set.rs
  src/integer/mat_poly_over_z/sort.rs
  src/integer/mat_z/set.rs
  src/integer/mat_z/sort.rs
  src/integer_mod_q/mat_polynomial_ring_zq/set.rs
  src/integer_mod_q/mat_polynomial_ring_zq/sort.rs
  src/integer_mod_q/mat_zq/inverse.rs
  src/integer_mod_q/mat_zq/set.rs
  src/integer_mod_q/mat_zq/solve.rs
  src/integer_mod_q/mat_zq/sort.rs
  src/rational/mat_q/cholesky_decomp.rs
  src/rational/mat_q/set.rs
  src/rational/mat_q/sort.rs
  src/traits.rs
Labels: enhancement📈

#503 Extend remainder trait
  src/integer/mat_poly_over_z/arithmetic/modulo.rs
  src/integer/mat_z/arithmetic/modulo.rs
  src/integer/poly_over_z/arithmetic/modulo.rs
  src/integer/z/arithmetic/modulo.rs
  src/integer_mod_q/mat_polynomial_ring_zq/set.rs
  src/integer_mod_q/modulus_polynomial_ring_zq/cmp.rs
  src/integer_mod_q/modulus_polynomial_ring_zq/from.rs
  src/integer_mod_q/modulus_polynomial_ring_zq/get.rs
  src/integer_mod_q/modulus_polynomial_ring_zq/unsafe_functions.rs
Labels: bug🐛, enhancement📈

#487 Revise decimal representation of `Q`, `MatQ` and `PolyOverQ`
  src/rational/mat_q/to_string.rs
  src/rational/poly_over_q/to_string.rs
  src/rational/q/to_string.rs
Labels: performance⚡

#504 update criterion dependency
  Cargo.toml
Labels: hotfix🔥

#491 Add `unsafe` Setters
  src/integer/mat_poly_over_z/unsafe_functions.rs
  src/integer/mat_z/unsafe_functions.rs
  src/integer/poly_over_z/unsafe_functions.rs
  src/integer/z/unsafe_functions.rs
  src/integer_mod_q/mat_polynomial_ring_zq/unsafe_functions.rs
  src/integer_mod_q/mat_zq/unsafe_functions.rs
  src/integer_mod_q/modulus/unsafe_functions.rs
  src/integer_mod_q/modulus_polynomial_ring_zq/unsafe_functions.rs
  src/integer_mod_q/poly_over_zq/unsafe_functions.rs
  src/integer_mod_q/polynomial_ring_zq/unsafe_functions.rs
  src/integer_mod_q/z_q/unsafe_functions.rs
  src/macros/unsafe_passthrough.rs
  src/rational/mat_q/unsafe_functions.rs
  src/rational/poly_over_q/unsafe_functions.rs
  src/rational/q/unsafe_functions.rs
Labels: enhancement📈

#489 `Add` & `Sub` between `MatQ` & `MatZ`
  src/integer/mat_z/arithmetic/sub.rs
  src/rational/mat_q/arithmetic/add.rs
  src/rational/mat_q/arithmetic/sub.rs
Labels: enhancement📈
